Repository cloud-project-groupH/theme-explorer-japan-fe, pull requests merged in 2024-12, with the labels that each got.

#20 [Refactor/HW-19]설문 페이지 버그 수정
  itshonigo/lib/survey_main_widget.dart
Labels: refactor

#21 [Feature/HW-20]로그인 버튼 api 설정
  itshonigo/android/app/src/main/AndroidManifest.xml
  itshonigo/ios/Runner/Info.plist
  itshonigo/lib/login_page_widget.dart
  itshonigo/lib/main.dart
  itshonigo/pubspec.lock
  itshonigo/pubspec.yaml
Labels: feat

#22 [Feature/SH-01f] 도메인 모델 추가 및 디렉토리 구조 변경
  itshonigo/lib/entities/member/member.dart
  itshonigo/lib/entities/place/like.dart
  itshonigo/lib/entities/place/place.dart
  itshonigo/lib/entities/place/visited.dart
  itshonigo/lib/login_page_widget.dart
  itshonigo/lib/pages/chat_room.dart
  itshonigo/lib/pages/chat_room_list.dart
  itshonigo/lib/pages/likes_page.dart
  itshonigo/lib/pages/location_list.dart
  itshonigo/lib/pages/location_page.dart
  itshonigo/lib/pages/login_page_widget.dart
  itshonigo/lib/pages/main.dart
  itshonigo/lib/pages/main_page.dart
  itshonigo/lib/pages/my_page.dart
  itshonigo/lib/pages/survey_main_widget.dart
Labels: feat, refactor

#23 [Feature/SH-02f] PR 템플릿 추가
  .github/pull_request_template.md
Labels: feat

#25 [Feature/SH-03f] flutter sdk를 이용한 카카오 로그인 구현
  .gitignore
  itshonigo/.gitignore
  itshonigo/devtools_options.yaml
  itshonigo/ios/Flutter/Debug.xcconfig
  itshonigo/ios/Flutter/Release.xcconfig
  itshonigo/ios/Podfile
  itshonigo/ios/Podfile.lock
  itshonigo/ios/Runner.xcodeproj/project.pbxproj
  itshonigo/ios/Runner.xcworkspace/contents.xcworkspacedata
  itshonigo/ios/Runner/Base.lproj/Main.storyboard
  itshonigo/ios/Runner/Info.plist
  itshonigo/lib/main.dart
  itshonigo/lib/pages/likes_page.dart
  itshonigo/lib/pages/login_page_widget.dart
  itshonigo/lib/pages/main.dart
  itshonigo/lib/pages/survey_main_widget.dart
  itshonigo/macos/Flutter/Flutter-Debug.xcconfig
  itshonigo/macos/Flutter/Flutter-Release.xcconfig
  itshonigo/macos/Flutter/GeneratedPluginRegistrant.swift
  itshonigo/macos/Podfile
  itshonigo/macos/Podfile.lock
  itshonigo/macos/Runner.xcodeproj/project.pbxproj
  itshonigo/macos/Runner.xcworkspace/contents.xcworkspacedata
  itshonigo/pubspec.lock
  itshonigo/pubspec.yaml
  itshonigo/windows/flutter/generated_plugin_registrant.cc
  itshonigo/windows/flutter/generated_plugins.cmake
Labels: feat

#27 [Refactor/HW-23]버그 수정
  itshonigo/lib/pages/survey_sixth.dart
Labels: refactor

#28 [Feature/HW-24]설문 페이지 라우팅 설정
  itshonigo/lib/main.dart
  itshonigo/lib/pages/main_page.dart
  itshonigo/lib/pages/survey_fifth.dart
  itshonigo/lib/pages/survey_fouth.dart
  itshonigo/lib/pages/survey_last.dart
  itshonigo/lib/pages/survey_main_widget.dart
  itshonigo/lib/pages/survey_secondary.dart
  itshonigo/lib/pages/survey_sixth.dart
  itshonigo/lib/pages/survey_third.dart
Labels: feat

#31 [Feature/SH-07f] 사용자 정보 로딩 설정
  itshonigo/ios/Podfile.lock
  itshonigo/lib/entities/member/member.dart
  itshonigo/lib/entities/member/member_provider.dart
  itshonigo/lib/main.dart
  itshonigo/lib/pages/login_page_widget.dart
  itshonigo/lib/pages/main_page.dart
  itshonigo/lib/pages/my_page.dart
  itshonigo/lib/pages/survey/confirm_survey.dart
  itshonigo/linux/flutter/generated_plugin_registrant.cc
  itshonigo/linux/flutter/generated_plugins.cmake
  itshonigo/macos/Flutter/GeneratedPluginRegistrant.swift
  itshonigo/pubspec.lock
  itshonigo/pubspec.yaml
  itshonigo/windows/flutter/generated_plugin_registrant.cc
  itshonigo/windows/flutter/generated_plugins.cmake
Labels: feat

#33 [Feature/HW-25]앱 아이콘 추가
  itshonigo/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  itshonigo/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  itshonigo/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  itshonigo/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  itshonigo/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/100.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/102.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/1024.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/114.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/120.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/128.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/144.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/152.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/16.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/167.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/172.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/180.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/196.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/20.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/216.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/256.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/29.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/32.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/40.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/48.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/50.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/512.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/55.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/57.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/58.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/60.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/64.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/66.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/72.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/76.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/80.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/87.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/88.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/92.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  itshonigo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
Labels: feat
